[[CURRENCIES]]
code="DSC"
issuer=""
status="live"
display_decimals=4
name="DIEGO STABLE COIN"
fixed_number=no
desc="DIEGO STABLE COIN"MOVE MONEY QUICKLY,RELIABLY.DSC is shorthand for DIEGOSTABLECOIN.
conditions="There will only ever be 100,000,000 DSC tokens in existence."
image="https://DIEGOSTABLECOIN.org/img/XLB_icon.png"
anchored="yes"

[DOCUMENTATION]
ORG_NAME="misfits-stellar-services"
ORG_URL="https://misfitsstellaranchorservices.com"
ORG_LOGO="https://stellarpay.org/img/XLB_icon.png"
ORG_DESCRIPTION="Connecting the world to crypto.The easy way to send, receive, store, and trade digital currencies."
ORG_PHYSICAL_ADDRESS=""
ORG_OFFICIAL_EMAIL="misfits@stellarmisfits.com"
ORG_TWITTER=""
ORG_REDDIT=""
ORG_GITHUB="misfits-stellar-services"
ORG_MEDIUM=""
